import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {humanReviewTemplate,validateHumanReview} from '../src/eval/human-review.ts';
import {reviewHtml} from '../eval/human-review.mjs';
const corpus=JSON.parse(await readFile(new URL('../eval/cases.json',import.meta.url),'utf8'));
const hash=JSON.parse(await readFile(new URL('../eval/corpus.lock.json',import.meta.url),'utf8')).sha256;
function completed(){const r=humanReviewTemplate(corpus.cases,hash);r.reviewer={name:'Synthetic test reviewer',kind:'human',independentOfOriginalAnnotation:true};r.humanAttestation=true;r.submittedAt='2026-09-20T12:00:00Z';r.cases.forEach((row,i)=>Object.assign(row,{verdict:'accept',bugExists:corpus.cases[i].expected==='defect'?'yes':'not_applicable',cleanIsClean:corpus.cases[i].expected==='clean'?'yes':'not_applicable',expectedBehavior:'sufficient',severity:corpus.cases[i].severity,graphBias:'none',rationale:'Synthetic validator test; not a real annotation.'}));return r;}
test('review preparation never upgrades an annotation or changes frozen labels',()=>{const before=JSON.stringify(corpus);const r=validateHumanReview(humanReviewTemplate(corpus.cases,hash),corpus.cases,hash);assert.equal(r.reviewed,0);assert.equal(r.complete,false);assert(r.annotations.every(a=>a.annotationProvenance.status==='pending_human_review'));assert.equal(JSON.stringify(corpus),before);});
test('human name, independence, attestation and valid date are required for completed rows',()=>{for(const mutate of [r=>r.reviewer.name='',r=>r.reviewer.kind='agent',r=>r.reviewer.independentOfOriginalAnnotation=false,r=>r.reviewer.independentOfOriginalAnnotation='true',r=>r.humanAttestation=false,r=>r.submittedAt='invalid']){const r=completed();mutate(r);assert.throws(()=>validateHumanReview(r,corpus.cases,hash));}});
test('corpus hash, exact 20 case identities and fixed SHAs bind review receipts',()=>{for(const mutate of [r=>r.corpusSha256='bad',r=>r.cases.pop(),r=>r.cases[1]=r.cases[0],r=>r.cases[0].headSha='bad']){const r=completed();mutate(r);assert.throws(()=>validateHumanReview(r,corpus.cases,hash));}});
test('all five assessments and a rationale are necessary; disagreements cannot silently accept gold',()=>{for(const field of ['bugExists','cleanIsClean','expectedBehavior','severity','graphBias','rationale']){const r=completed();r.cases[0][field]='';assert.throws(()=>validateHumanReview(r,corpus.cases,hash));}const r=completed();r.cases[0].severity='low';assert.throws(()=>validateHumanReview(r,corpus.cases,hash));r.cases[0].verdict='needs_revision';const receipt=validateHumanReview(r,corpus.cases,hash);assert.equal(receipt.annotations[0].annotationProvenance.status,'human_reviewed_disputed');assert.equal(receipt.allAccepted,false);assert.equal(corpus.cases[0].severity,'high');});
test('partial human review upgrades only actually reviewed rows',()=>{const r=completed();r.cases[0].verdict='pending';const receipt=validateHumanReview(r,corpus.cases,hash);assert.equal(receipt.reviewed,19);assert.equal(receipt.complete,false);assert.equal(receipt.annotations[0].annotationProvenance.status,'pending_human_review');});
test('packet scripts parse and embedded source cannot close script tags',()=>{const html=reviewHtml({...corpus,cases:[{...corpus.cases[0],headFiles:{'x.py':'</script><script>alert(1)</script>'}}]},humanReviewTemplate(corpus.cases,hash));assert(!html.includes('</script><script>alert'));const script=html.match(/<script>([\s\S]*)<\/script>/)[1];assert.doesNotThrow(()=>new Function(script));assert(!html.includes('RATIO-001'));});
