import test from 'node:test';
import assert from 'node:assert/strict';
import {explanationStateId as id,retainStructuralPaths} from '../src/experiments/locagent/path-retention.ts';
function fixture(nodes,pairs){const states=nodes.map(([name,step])=>({entity:{id:name,snapshotId:'s',path:name+'.py',qualifiedName:name,name,kind:'function',startLine:1,endLine:3,startColumn:0,endColumn:1},rootEntityId:'A',patternId:'calls',stepIndex:step,direction:'downstream'}));return {snapshotId:'s',generationId:'g',states,links:pairs.map(([a,b],i)=>({previousStateId:id(states[a]),stateId:id(states[b]),direction:'downstream',edge:{id:'e'+i,snapshotId:'s',fromId:states[a].entity.id,toId:states[b].entity.id,relation:'CALLS',resolution:'resolved_scoped',sourcePath:states[a].entity.path,sourceLine:2,sourceEndLine:2,sourceColumn:0,sourceEndColumn:1,siteId:'site'+i,resolverVersion:'frozen'}}))};}
test('diamond retains both explanations while the reached terminal state stays unique',()=>{const f=fixture([['A',0],['B',1],['C',1],['D',2]],[[0,1],[0,2],[1,3],[2,3]]),r=retainStructuralPaths(f),d=r.states.filter(s=>s.entity.id==='D');assert.equal(d.length,1);assert.deepEqual(d[0].paths.map(p=>p.entityIds),[['A','B','D'],['A','C','D']]);assert.equal(r.metrics.maxParentsPerState,2);assert.equal(r.metrics.additionalRetainedPredecessors,1);assert.deepEqual(r,retainStructuralPaths({...f,links:[...f.links].reverse()}));});
test('cycle explanations are acyclic in step space and bounded',()=>{const f=fixture([['A',0],['B',1],['C',2],['A',3]],[[0,1],[1,2],[2,3]]),r=retainStructuralPaths(f);assert.equal(r.states.length,4);assert.equal(r.metrics.retainedParentLinks,3);assert.deepEqual(r.states.find(s=>s.stepIndex===3).paths[0].entityIds,['A','B','C','A']);assert.throws(()=>retainStructuralPaths({...f,links:[...f.links,{...f.links[0],previousStateId:id(f.states[3])}]}),/predecessor/);});
test('many offered parents retain at most two stable distinct links and two paths',()=>{const f=fixture([['A',0],['B',1],['C',1],['D',1],['E',2]],[[0,1],[0,2],[0,3],[1,4],[2,4],[3,4]]);f.links.push(f.links[3]);const r=retainStructuralPaths(f);assert.equal(r.metrics.maxParentsPerState,2);assert.equal(r.metrics.omittedParents,1);assert.equal(r.metrics.duplicateLinks,1);assert.ok(r.states.every(s=>s.paths.length<=2));});
test('foreign snapshot, unresolved edges and skipped steps cannot become explanation evidence',()=>{const f=fixture([['A',0],['B',1]],[[0,1]]);assert.throws(()=>retainStructuralPaths({...f,snapshotId:'other'}),/state/);assert.throws(()=>retainStructuralPaths({...f,links:[{...f.links[0],edge:{...f.links[0].edge,resolution:'candidate'}}]}),/definite/);});
import {progressiveWalk,STRUCTURAL_PATTERNS} from '../src/experiments/locagent/patterns.ts';
import {retentionTraceFromFrozen} from '../eval/path-retention-replay.mjs';
test('frozen progressive diamond expands the shared state once and replay restores both parents',()=>{const f=fixture([['A',0],['B',1],['C',1],['D',2],['E',3]],[[0,1],[0,2],[1,3],[2,3],[3,4]]),symbols=new Map(f.states.map(s=>[s.entity.id,s.entity])),edges=f.links.map(l=>l.edge),visits=[];let dExpansions=0;
 const access={entity:id=>symbols.get(id),compare:(a,b)=>a.id<b.id?-1:a.id>b.id?1:0,neighbors:(entityId,direction)=>{if(entityId==='D'&&direction==='downstream')dExpansions++;return new Proxy(edges.filter(e=>(direction==='downstream'?e.fromId:e.toId)===entityId),{get(target,key){if(typeof key==='string'&&/^\d+$/.test(key)&&target[key])visits.push({fromStateEntity:entityId,direction,edge:target[key]});return Reflect.get(target,key);}});}};
 const search=progressiveWalk([symbols.get('A')],STRUCTURAL_PATTERNS,{maxVisitedNodes:30,maxVisitedEdges:200,maxExpandedStates:200},4,access);
 const row={searches:[search],pack:{snapshotId:'s',generationId:'g'}},plan={snapshotId:'s',generationId:'g',queries:[{startEntities:['A']}],request:{template:'STRUCTURAL_ESCALATION'}},replay=retentionTraceFromFrozen(row,plan,{visits}),r=retainStructuralPaths(replay.input),d=r.states.find(s=>s.entity.id==='D'&&s.patternId==='calls-out');
 assert.equal(dExpansions,1);assert.deepEqual(d.paths.map(p=>p.entityIds),[['A','B','D'],['A','C','D']]);assert.equal(new Set(replay.input.states.map(s=>s.entity.id)).size,new Set(search.discoveries.map(d=>d.entity.id)).size);
});
