import test from 'node:test';
import assert from 'node:assert/strict';
import {progressiveWalk,STRUCTURAL_PATTERNS} from '../src/experiments/locagent/patterns.ts';
import {LocAgentRetrieval} from '../src/experiments/locagent/retrieval.ts';
const limits={maxVisitedNodes:30,maxVisitedEdges:200,maxExpandedStates:200};
function fixture(pairs){const symbols=[...new Set(pairs.flatMap(([a,b])=>[a,b]))].map(id=>({id,snapshotId:'s',path:id.startsWith('same')?'same.py':id+'.py',name:id,qualifiedName:id,kind:'function',startLine:1,endLine:3,startColumn:0,endColumn:1}));const relations=pairs.map(([fromId,toId,relation='CALLS'],i)=>({id:'e'+i,snapshotId:'s',fromId,toId,relation,resolution:'resolved_scoped',sourcePath:symbols.find(s=>s.id===fromId).path,sourceLine:2,sourceEndLine:2,sourceColumn:0,sourceEndColumn:1,siteId:'site'+i,resolverVersion:'frozen'}));const data={snapshotId:'s',generationId:'g',generationState:'ready',graphScope:'core',symbols,relations,sources:{},coverage:{eligibleFiles:symbols.length,indexedFiles:symbols.length,parseIncompleteFiles:0,unsupportedFiles:0},warnings:[]};return {data,roots:[symbols[0]],access:{entity:id=>symbols.find(s=>s.id===id),neighbors:(id,direction)=>relations.filter(e=>(direction==='downstream'?e.fromId:e.toId)===id),compare:(a,b)=>a.id<b.id?-1:a.id>b.id?1:0}};}
const run=(f,budget=limits,beam=4,signal)=>progressiveWalk(f.roots,STRUCTURAL_PATTERNS,budget,beam,f.access,signal);
test('V2 fair lanes discover callers before a high-fanout downstream lane consumes budget',()=>{const f=fixture([...Array.from({length:40},(_,i)=>['root','out'+i]),['caller','root']]),r=run(f,{...limits,maxVisitedNodes:8});assert.ok(r.discoveries.some(d=>d.entity.id==='caller'));assert.equal(r.stopReason,'visited_nodes');assert.equal(r.visitedNodes,8);});
test('V2 a CALLS lane never switches direction or silently mixes relation types',()=>{const r=run(fixture([['root','a'],['back','a'],['a','module','IMPORTS'],['root','mod','IMPORTS'],['consumer','mod','IMPORTS']]));assert.ok(!r.discoveries.some(d=>d.entity.id==='back'||d.entity.id==='module'));const consumer=r.discoveries.find(d=>d.entity.id==='consumer');assert.equal(consumer.patternId,'imports');assert.equal(consumer.depth,2);});
test('V2 same-file intermediate nodes stay in the frontier and parent paths remain exact',()=>{const r=run(fixture([['same0','same1'],['same1','same2'],['same2','target']]));let d=r.discoveries.find(d=>d.entity.id==='target');assert.ok(d);const path=[];while(d){path.unshift(d.entity.id);d=r.discoveries[d.parentStateId];}assert.deepEqual(path,['same0','same1','same2','target']);});
test('V2 beam selection is deterministic and reports pruned frontier separately from candidates',()=>{const f=fixture([...Array.from({length:7},(_,i)=>['root','branch'+i]),['branch6','terminal']]),a=run(f),b=run(f);assert.deepEqual(a,b);assert.ok(a.frontierDropped>=3);assert.ok(a.discoveries.some(d=>d.entity.id==='branch6'));assert.ok(!a.discoveries.some(d=>d.entity.id==='terminal'));assert.ok(a.droppedFrontier.some(d=>d.entityId==='branch6'&&d.patternId==='calls-out'));});
test('V2 exact bounds, cycles, empty adjacency and cancellation remain finite',()=>{const f=fixture([['root','a'],['a','root'],['a','leaf']]);for(const budget of [{...limits,maxVisitedEdges:1},{...limits,maxExpandedStates:1}]){const r=run(f,budget);assert.ok(r.visitedEdges<=budget.maxVisitedEdges);assert.ok(r.expandedStates<=budget.maxExpandedStates);}assert.ok(run(f).discoveries.length<30);let n=0;assert.throws(()=>run(f,limits,4,{throwIfAborted(){if(++n===5)throw Error('cancelled');}}),/cancelled/);});
test('V2 whole rooted candidate paths obey delivery bytes without changing source windows',()=>{const f=fixture([['same0','same1'],['same1','same2'],['same2','target']]),r=new LocAgentRetrieval(f.data),q={startEntities:['same0'],direction:'both',maxHops:3,maxNodes:30,maxBytes:8192,entityTypeFilter:[],relationTypeFilter:['CALLS','IMPORTS','INHERITS']};const a=r.patternTraverse(q);assert.ok(a.items.some(i=>i.entityId==='target'));assert.equal(a.edges.length,3);assert.ok(Buffer.byteLength(JSON.stringify(a))<=8192);const small=r.patternTraverse({...q,maxBytes:2048});assert.ok(Buffer.byteLength(JSON.stringify(small))<=2048);assert.equal(small.searchMetrics.visitedNodes,a.searchMetrics.visitedNodes);});
